singleQuote: true
printWidth: 120
trailingComma: all

plugins:
  - '@ianvs/prettier-plugin-sort-imports'

importOrder:
  - <BUILTIN_MODULES>
  - '^react$'
  - '^next(.*)$'
  - <THIRD_PARTY_MODULES>
  - ''
  - ^@/lib/(.*)$
  - '^@/(.*)$'
  - ''
  - '^../(.*)$'
  - '^./(.*)$'
  - '^[./]'
